# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tagged Release

on:
  push:
    tags: [ "v*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  create-nuget-package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - name: Pack NuGet Package
        run: dotnet pack AviationCalcUtilNet.csproj -o ${{ github.workspace }}/out/nuget --include-symbols
      - name: Archive NuGet Files
        uses: actions/upload-artifact@v4
        with:
          name: AviationCalcUtilNet-NuGet
          path: |
            ${{ github.workspace }}/out/nuget/*
  create-github-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-latest
    needs: create-nuget-package
    steps:
      - name: Download Nuget Files
        uses: actions/download-artifact@v4
        with:
          name: AviationCalcUtilNet-NuGet
          path: ${{ github.workspace }}/NuGet
      - name: Extract Nuget Packages
        run: unzip ${{ github.workspace }}/NuGet/*.nupkg -d ${{ github.workspace }}/NuGet
      - name: Tar Binaries
        run: |
          mkdir -p ${{ github.workspace}}/bins
          cd ${{ github.workspace }}/NuGet/lib
          tar -czvf ${{ github.workspace}}/bins/AviationCalcUtilNet.tar.gz *.*
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ github.workspace}}/bins/*.tar.gz
  upload-nuget-package:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-22.04
    needs: create-nuget-package
    steps:
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'
      - name: Download NuGet Packages Contents
        uses: actions/download-artifact@v4
        with:
          name: AviationCalcUtilNet-NuGet
          path: ${{ github.workspace }}/nuget
      - name: Upload NuGet Package
        run: |
          cd ${{ github.workspace }}/nuget
          nuget push *.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
